[package]
name = "git-leave"
version = "1.6.0"
description = "Check for unsaved or uncommitted changes on your machine."
authors = ["Milo Moisson <milomoisson@gmail.com>"]
repository = "https://github.com/MrNossiom/git-leave"
keywords = ["crawler", "git", "cli"]
categories = ["development-tools"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
color-eyre = "0.6.2"
console = "0.15.5"
crossbeam = "0.8.2"
dirs = "5.0"
git2 = "0.17.0"
indicatif = "0.17.3"
num_cpus = "1.15.0"

[dependencies.label-logger]
git = "https://github.com/MrNossiom/label-logger"
rev = "60c65c0"
features = ["indicatif"]
