[package]
name = "git-leave"
description = "Check for unsaved or uncommitted changes on your machine."
authors = ["Milo Moisson <milomoisson@gmail.com>"]
repository = "https://github.com/MrNossiom/git-leave"
license = "MIT"
version = "1.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
crossbeam = "0.8.1"
dirs = "4.0"
git2 = "0.13.17"
label-logger = "1.0.0-alpha.4"
num_cpus = "1.13.1"
