[package]
name = "git-leave"
version = "1.6.1"
description = "Check for unsaved or uncommitted changes on your machine"
authors = ["Milo Moisson <milomoisson@gmail.com>"]
repository = "https://github.com/MrNossiom/git-leave"
keywords = ["crawler", "git", "cli"]
categories = ["development-tools"]
license = "CECILL-2.1"
edition = "2021"

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
color-eyre = "0.6.2"
console = "0.15.7"
crossbeam = "0.8.2"
dirs = "5.0"
git2 = "0.17.2"
indicatif = "0.17.5"
label-logger = { version = "0.2.0", features = ["indicatif"] }
num_cpus = "1.15.0"
