[package]
name = "git-leave"
description = "Check for unsaved or uncomitted changes on your machine."
authors = ["Milo Moisson <milomoisson@gmail.com>"]
repository = "https://github.com/MrNossiom/git-leave"
license = "MIT"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
git2 = "0.13.17"
term_size = "0.3.2"
yansi = "0.5.0"
