[package]
name = "git-leave"
authors = ["Milo Moisson <milomoisson@gmail.com>"]
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
git2 = "0.13.17"
term_size = "0.3.2"
yansi = "0.5.0"
